version: '3.8'

services:
  postgres:
    container_name: nest-clean-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest_clean
      PGDATA: /data/postgres
    volumes:
      - pgdata:/data/postgres

  localstack:
    container_name: nest-clean-localstack
    image: localstack/localstack:4.6.0
    ports:
      - 4566:4566
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DEBUG=0
    volumes:
      - localstack-data:/var/lib/localstack

volumes:
  pgdata:
    driver: local
  localstack-data:
    driver: local