@baseUrl = http://localhost:3000

@authToken = {{signin.response.body.access_token}}
@refreshToken = {{signin.response.body.refresh_token}}

POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "password": "12345678"
}

###

# @name signin

POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "12345678"
}

###

# @name refresh

POST {{baseUrl}}/auth/refresh
Content-Type: application/json
Authorization: Bearer {{refreshToken}}

###

POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}
